environment:
  resources:
    aws:
      - resource:
          type: rds
          configuration:
            engine: mysql
            flavor: db.m1.medium
  app_deployment:
    target: aws
    type: ecs
    instance_type: t2.medium
 

