environment:
  resources:
    aws:
      - resource:
          type: rds
          configuration:
            engine: mysql
            flavor: db.m1.medium
          policy:
            access: open
  app_deployment:
    target: local

 

